### ISSUE TITLE
Trying to figure out how does this work

### ISSUE THREAD

**Issue by EVOLCORE** [DrAbcOfficial/TinyHalflifeServer#1]
Trying to setup to work on cs 1.6 server

Debug console:
[debug.txt](https://github.com/user-attachments/files/18153184/debug.txt)

game console:

] connect 127.0.0.1:27016 
Connecting to 127.0.0.1:27016 ...
Trying p48/auth3/revEmu... 
Connection accepted by 127.0.0.1:27016
Host_Error: UserMsg: Not Present on Client 111

config.json:
`{
  "Product": "counter-strike",
  "AppId": 10,
  "Version": "1.1.2.7/Stdio,48,3428",
  "GSLT": "*secret*",
  "Port": 27016,
  "GoldSrc": true,
  "Debug": true,
  "Text": {
    "Kicked": "You have been banned from this server."
  },
  "RDIP": {
    "Enable": true,
    "IP": "127.0.0.1",
    "Port": 27015,
    "Method": 0
  },
  "ServerInfo": {
    "Name": "CS 1.6 Server",
    "Map": "de_dust2",
    "GameFolder": "cstrike",
    "Description": "Counter-Strike",
    "MaxClients": 32,
    "Protocol": 48,
    "Type": 100,
    "OS": 119,
    "Passworded": false,
    "Moded": true,
    "VAC": true,
    "FakeClients": 0,
    "Players": [
      {
        "Name": "PlayerOne",
        "Score": 150,
        "Duration": 420
      },
      {
        "Name": "GamerX",
        "Score": 185,
        "Duration": 560
      },
      {
        "Name": "ShadowStrike",
        "Score": 120,
        "Duration": 350
      },
      {
        "Name": "AceKiller",
        "Score": 210,
        "Duration": 780
      },
      {
        "Name": "QuickScope",
        "Score": 100,
        "Duration": 200
      },
      {
        "Name": "NinjaFury",
        "Score": 95,
        "Duration": 500
      },
      {
        "Name": "SilentWolf",
        "Score": 250,
        "Duration": 950
      },
      {
        "Name": "FlashBangMaster",
        "Score": 80,
        "Duration": 320
      },
      {
        "Name": "GrenadeGod",
        "Score": 190,
        "Duration": 740
      },
      {
        "Name": "HeadshotKing",
        "Score": 225,
        "Duration": 880
      },
      {
        "Name": "TheHunter",
        "Score": 130,
        "Duration": 420
      },
      {
        "Name": "KillStealer",
        "Score": 140,
        "Duration": 540
      },
      {
        "Name": "FrostByte",
        "Score": 160,
        "Duration": 630
      },
      {
        "Name": "DarkRanger",
        "Score": 110,
        "Duration": 410
      },
      {
        "Name": "BulletStorm",
        "Score": 170,
        "Duration": 620
      },
      {
        "Name": "XxSilentKillerxX",
        "Score": 145,
        "Duration": 540
      },
      {
        "Name": "WolfPack",
        "Score": 200,
        "Duration": 750
      },
      {
        "Name": "SharpShooter",
        "Score": 215,
        "Duration": 850
      },
      {
        "Name": "LastBullet",
        "Score": 105,
        "Duration": 330
      },
      {
        "Name": "RedBullet",
        "Score": 185,
        "Duration": 710
      },
      {
        "Name": "DarkKnight",
        "Score": 160,
        "Duration": 600
      },
      {
        "Name": "SnipeMaster",
        "Score": 180,
        "Duration": 720
      },
      {
        "Name": "Maverick",
        "Score": 125,
        "Duration": 500
      },
      {
        "Name": "FalconEye",
        "Score": 210,
        "Duration": 800
      },
      {
        "Name": "SniperElite",
        "Score": 95,
        "Duration": 400
      },
      {
        "Name": "HeadHunter",
        "Score": 150,
        "Duration": 590
      },
      {
        "Name": "AceSniper",
        "Score": 175,
        "Duration": 650
      },
      {
        "Name": "IronFist",
        "Score": 130,
        "Duration": 480
      },
      {
        "Name": "ChaosTheory",
        "Score": 120,
        "Duration": 460
      },
      {
        "Name": "DarkShadow",
        "Score": 200,
        "Duration": 750
      },
      {
        "Name": "GhostWalker",
        "Score": 95,
        "Duration": 330
      }
    ],
    "Rules": [
      {
        "Name": "TeamSwitch",
        "Value": "Players must switch teams after every round."
      },
      {
        "Name": "Friendly Fire",
        "Value": "No"
      },
      {
        "Name": "NoCamping",
        "Value": "Camping is not allowed, move around!"
      },
      {
        "Name": "Cheating",
        "Value": "Cheating is strictly prohibited. Use of aimbots, wallhacks, or any form of cheating will result in a ban."
      },
      {
        "Name": "Language",
        "Value": "Offensive language or abuse will lead to a kick or ban."
      }
    ]
  }
}
`

**Comment by DrAbcOfficial** [comment]
it looks working perfectly to me

**Comment by DrAbcOfficial** [comment]
by the way, your GSLT leaked, change it as soon as possible

**Comment by EVOLCORE** [comment]
To me maybe is not working because i am testing it via Windows platform, btw how i can contact you, do you have Discord or Kakao talk ?

**Comment by DrAbcOfficial** [comment]
nah, I don't use either of those, and if you're asking about rdip, the program only contains the code for stufftext and part of the code for full udp forwarding, and I don't want to and won't risk a felony by sharing the code for spoofing udp packets
